const GT = 'https://seeklogo.com/images/G/gujarat-titans-ipl-logo-6962504B75-seeklogo.com.png';
const SRH = 'https://logowik.com/content/uploads/images/sunrisers-hyderabad5129.jpg';
const CSK ='https://logowik.com/content/uploads/images/chennai-super-kings3461.jpg';
const DC = 'https://logowik.com/content/uploads/images/delhi-capitals3041.jpg';
const PK = 'https://logowik.com/content/uploads/images/punjab-kings6722.logowik.com.webp';
const KKR = 'https://logowik.com/content/uploads/images/kolkata-knight-riders6292.jpg';
const RCB = 'https://logowik.com/content/uploads/images/rcb-royal-challengers-bangalore7895.logowik.com.webp';
const RR = 'https://seeklogo.com/images/I/ipl-rajasthan-royals-logo-F69DDCEF15-seeklogo.com.png';
const MI = 'https://logowik.com/content/uploads/images/mumbai-indians2544.jpg';
const LSG = 'https://logowik.com/content/uploads/images/lucknow-super-giants3550.logowik.com.webp';

const lsg = 'Lucknow Super Giants';
const gt = 'Gujarat Titans';
const csk = 'Chennai Super Kings';
const dc = 'Delhi Capitals';
const pk = 'Punjab Kings';
const kkr = 'Kolkata Knight Riders';
const rcb = 'Royal Challengers Bangalore';
const rr = 'Rajasthan Royals';
const mi = 'Mumbai Indians';
const srh = 'Sunrisers Hyderabad';


const SportsLists = [
    {
        cricketPrice: [750, 1550, 1850, 3500, 6500, 12500, 15000],
        cricketPlace: ['Ground Floor', 'First Floor', 'First Terrace', 'Second Floor', 'Second Terrace', 'Third Floor', 'Third Terrace'],

        footballPrice: [500, 1000, 1200, 2500, 5000, 10000, 12000],

        cricket:[
            {
                id: 1,
                img: 'https://i.pinimg.com/736x/ee/d9/fb/eed9fb1e65f3d390fb6e12d0c83011fd.jpg',
                largeImg: 'https://i.pinimg.com/736x/c5/6b/e8/c56be8c0fb282b258f13f347e8a818e4.jpg',
                event: 'GT vs SRH',
                img1: SRH,
                img2: GT,
                date: 'FRI 02',
                time: '07:30 P.M',
                month: 'May',
                venue: 'Narendra Modi Stadium',
                location: 'Ahmedabad, India',
                team1: srh,
                team2: gt,
                game:'Cricket',
                duration:3,
                tickets: 2,
                layout: 'Outdoor',
                seating:'Seated',
                kids: 'Yes',
                on: '2025-05-02',
                type: 'IPL',
                address: 'Stadium Road Motera, Sabarmati, Ahmedabad, Gujarat 380005',
                priceStarts: 499,
                des: `This isn’t a match. It’s a GT homegrown takeover. As Gujarat Titans roll back into Ahmedabad, the atmosphere is electric. And the real chaos starts with the ball. Rashid Khan’s spin is still an unsolved mystery, while Sai Kishore's spin, Siraj’s pace and Rabada’s bounce are built to wreck stumps and egos. But it’s not just the bowlers bringing the heat; GT’s top order is just as ruthless. Buttler’s brute power, Gill’s effortless elegance and Sai Sudharsan’s icy composure are primed to turn totals into target practice. This isn’t just a home game, it’s a homecoming. And the Titans are ready to take what’s theirs.`
            },
    
        {
            id: 2,
            img: 'https://i.pinimg.com/736x/e8/5f/4a/e85f4afd84b0ead07a96aa215a09ba91.jpg',
            largeImg: 'https://i.pinimg.com/736x/4c/c7/93/4cc793568be4f6990bf66d62c81df448.jpg',
            event: 'LSG vs PK',
            img1: LSG,
            img2: PK,
            date: 'SUN 4',
            time: '07:30 P.M',
            month: 'May',
            venue: 'Himachal Pradesh Cricket Association Stadium',
            location: 'Dharamshala, India',
            team1: lsg,
            team2: pk,
            game:'Cricket',
            duration:3,
            tickets: 2,
            layout: 'Outdoor',
            seating:'Seated',
            kids: 'Yes',
            on: '2025-05-04',
            type: 'IPL',
            priceStarts: 1000,
            address: 'HPCA Cricket Stadium, Distt-Kangra, Tehsil, Jawahar Nagar, Dharamshala, Himachal Pradesh 176215, India',
            des: `Get ready! The next lot of tickets is going live soon! The Punjab Kings are set to lock horns with the Lucknow Super Giants in what promises to be an electrifying clash. Set against the breathtaking backdrop of the Himalayas at the scenic Dharamsala stadium, this is a golden opportunity for PBKS to climb the table with confidence and momentum. Under Shreyas Iyer’s composed leadership, they’ll be looking to bring their fearless brand of cricket to the fore. Arshdeep’s pinpoint yorkers, Prabhsimran’s explosive starts, and Shashank’s finishing power give Punjab plenty of firepower. Add in Yuzvendra Chahal’s crafty spin and the all-round strength of Marcus Stoinis, and the bowling unit looks sharp. LSG, led by Rishabh Pant, will look to fire back with their game-changers like Nicholas Pooran and Mitchell Marsh. The battle between the two sides will be intense, with both teams hungry for a win. If Punjab can keep the pressure on and play to their strengths, this one could go firmly in their favor.`
            
        },
        {
            id: 3,
            img: 'https://i.pinimg.com/736x/fc/a0/fb/fca0fba2ee0f87437002a8851255e2e5.jpg',
            largeImg: 'https://i.pinimg.com/736x/5f/dc/89/5fdc8909579cdc4690c153e3fef1a888.jpg',
            event: 'SRH vs DC',
            img1: SRH,
            img2: DC,
            date: 'MON 05',
            time: '07:30 P.M',
            month: 'May',
            venue: 'Rajiv Gandhi International Cricket Stadium',
            location: 'Hyderabad, India',
            team1: srh,
            team2: dc,
            game:'Cricket',
            duration:3,
            tickets: 2,
            layout: 'Outdoor',
            seating:'Seated',
            kids: 'Yes',
            on: '2025-05-05',
            type: 'IPL',
            priceStarts: 1000,
            address: 'Stadium Road Motera, Sabarmati, Ahmedabad, Gujarat 380005',
            des: `SRH is back and ready to dominate at home. Klaasen’s powerful batting, Pat Cummins’ fierce spells and the relentless energy of Eshan Malinga make this team a powerhouse no one can underestimate. DC might have their stars, but there’s no match for the roar of the Orange Army. With every boundary, every wicket, and every nail-biting moment, SRH is setting the stage for an unforgettable battle. Get ready for a fierce clash at the fortress. This is where heroes are made, and legends rise. Don’t miss the electrifying showdown`
        },
        {
            id: 4,
            img: 'https://i.pinimg.com/736x/dc/fc/d2/dcfcd27b66d0bfd58760de3c6f49454d.jpg',
            largeImg: 'https://i.pinimg.com/736x/31/aa/16/31aa16d528d4ec07505838e8c56a3baa.jpg',
            event: 'KKR VS csk',
            img1: KKR,
            img2: CSK,
            team1: kkr,
            team2: csk,
            date: 'Thu 08',
            time: '07:30 P.M',
            month: 'May',
            venue: 'Eden Gardens',
            location: 'Kolkata, India',
            address: 'The Cricket Association of Bengal, DR BC Roy Club House, Eden Gardens, Kolkata - 700021',
            game:'Cricket',
            duration:3,
            tickets: 2,
            layout: 'Outdoor',
            seating:'Seated',
            kids: 'Yes',
            on: '2025-05-08',
            type: 'IPL',
            priceStarts: 900,
            des: `Book tickets for ${kkr} vs ${csk} IPL 2025 cricket for 7th MAy 2025 at Eden Gardens Stadium on BookItNow. Experience ${kkr} and ${csk} live at the Stadium this year.`
        },
        {
            id: 5,
            img: 'https://i.pinimg.com/736x/30/2c/49/302c49a642eaae717d65c136e9bebf69.jpg',
            largeImg: 'https://i.pinimg.com/736x/63/85/94/63859414bdd9de1a2cb977e9219f1510.jpg',
            event: 'PK vs DC',
            img1: PK,
            img2: DC,
            team1: pk,
            team2: dc,
            date: 'Wed 07',
            time: '07:30 P.M',
            month: 'May',
            venue: 'Himachal Pradesh Cricket Association Stadium',
            location: 'Dharamshala, India',
            address: 'HPCA Cricket Stadium, Distt-Kangra, Tehsil, Jawahar Nagar, Dharamshala, Himachal Pradesh 176215, India',
            game:'Cricket',
            duration:3,
            tickets: 2,
            layout: 'Outdoor',
            seating:'Seated',
            kids: 'Yes',
            on: '2025-05-08',
            type: 'IPL',
            priceStarts: 1000,
            des: `The Punjab Kings return to action at the iconic Dharamshala stadium, set to face the Delhi Capitals in a high-stakes clash. Under Shreyas Iyer’s sharp captaincy, PBKS will be aiming to make a statement at home. Prabhsimran’s fearless batting, Shashank’s finishing, and Arshdeep’s brilliance with the ball have kept them in the hunt. Add Chahal’s spin mastery, and Punjab looks ready for any challenge. Delhi, led by Axar and backed by KL Rahul and Kuldeep Yadav, brings serious firepower. But in the shadow of the Himalayas, with the crowd roaring and Shreyas leading from the front, another win in red and gold could be on the horizon. With the playoff race tightening, every ball will count in this adrenaline-charged showdown. Expect fireworks as two explosive lineups collide under the Dharamsala lights, where legends are made and dreams come alive.`
        },
        {
            id: 6,
            img: 'https://i.pinimg.com/736x/5a/8e/be/5a8ebe53778b46039ee033137fd9a19a.jpg',
            largeImg: 'https://i.pinimg.com/736x/55/21/ee/5521ee2c00347a0ae607ed3f4def3006.jpg',
            event: 'LSG vs RCB',
            img1: LSG,
            img2: RCB,
            team1: lsg,
            team2: rcb,
            date: 'Fri 09',
            time: '07:30 P.M',
            month: 'May',
            venue: 'Ekana Cricket Stadium',
            location: 'Uttar Pradesh, India',
            address: 'Ekana Sportz City, Gomti Nagar, Lucknow, Ardonamau, Uttar Pradesh 226010',
            game:'Cricket',
            duration:3,
            tickets: 2,
            layout: 'Outdoor',
            seating:'Seated',
            kids: 'Yes',
            on: '2025-05-08',
            type: 'IPL',
            priceStarts: 1000,
            des: `Brace yourself for a blockbuster battle as Lucknow Super Giants take on Royal Challengers Bengaluru in a high-stakes IPL 2025 showdown! Get ready for massive sixes, fiery spells, and edge-of-the-seat action as LSG fights for victory. Be part of the Super Giants family and witness every boundary, wicket, and last-over thriller LIVE! Book your tickets now!  `
        },
        {
            id: 7,
            img: 'https://i.pinimg.com/736x/23/ee/dc/23eedced2c8851194143b7186d2663ce.jpg',
            largeImg: 'https://i.pinimg.com/736x/d3/4b/59/d34b5916107c9680d5d76ce896429599.jpg',
            event: 'SRH vs KKR',
            img1: SRH,
            img2: KKR,
            team1: srh,
            team2: kkr,
            date: 'SAT 10',
            time: '07:30 P.M',
            month: 'May',
            venue: 'Rajiv Gandhi International Cricket Stadium',
            location: 'Hyderabad, India',
            address: 'RGI Stadium Rd, Uppal, Hyderabad, Telangana 500039, India',
            game:'Cricket',
            duration:3,
            tickets: 2,
            layout: 'Outdoor',
            seating:'Seated',
            kids: 'Yes',
            on: '2025-05-10',
            type: 'IPL',
            priceStarts: 1000,
            des: `The Punjab Kings return to action at the iconic Dharamshala stadium, set to face the Delhi Capitals in a high-stakes clash. Under Shreyas Iyer’s sharp captaincy, PBKS will be aiming to make a statement at home. Prabhsimran’s fearless batting, Shashank’s finishing, and Arshdeep’s brilliance with the ball have kept them in the hunt. Add Chahal’s spin mastery, and Punjab looks ready for any challenge. Delhi, led by Axar and backed by KL Rahul and Kuldeep Yadav, brings serious firepower. But in the shadow of the Himalayas, with the crowd roaring and Shreyas leading from the front, another win in red and gold could be on the horizon. With the playoff race tightening, every ball will count in this adrenaline-charged showdown. Expect fireworks as two explosive lineups collide under the Dharamsala lights, where legends are made and dreams come alive.`
        },
        {
            id: 8,
            img: 'https://i.pinimg.com/736x/fc/45/5c/fc455c0544b22e9dd260bbd1cff7133a.jpg',
            largeImg: 'https://i.pinimg.com/736x/4e/54/0f/4e540f6932fc89571448d90159e01c74.jpg',
            event: 'GT vs LSG',
            img1: GT,
            img2: LSG,
            team1: gt,
            team2: lsg,
            date: 'WED 14',
            time: '07:30 P.M',
            month: 'May',
            venue: 'Narendra Modi Stadium',
            location: 'Ahmedabad, India',
            address: 'Stadium Road Motera, Sabarmati, Ahmedabad, Gujarat 380005',
            game:'Cricket',
            duration:3,
            tickets: 2,
            layout: 'Outdoor',
            seating:'Seated',
            kids: 'Yes',
            on: '2025-05-14',
            type: 'IPL',
            priceStarts: 499,
            des: `The Punjab Kings return to action at the iconic Dharamshala stadium, set to face the Delhi Capitals in a high-stakes clash. Under Shreyas Iyer’s sharp captaincy, PBKS will be aiming to make a statement at home. Prabhsimran’s fearless batting, Shashank’s finishing, and Arshdeep’s brilliance with the ball have kept them in the hunt. Add Chahal’s spin mastery, and Punjab looks ready for any challenge. Delhi, led by Axar and backed by KL Rahul and Kuldeep Yadav, brings serious firepower. But in the shadow of the Himalayas, with the crowd roaring and Shreyas leading from the front, another win in red and gold could be on the horizon. With the playoff race tightening, every ball will count in this adrenaline-charged showdown. Expect fireworks as two explosive lineups collide under the Dharamsala lights, where legends are made and dreams come alive.`
        },
        {
            id: 9,
            img: 'https://i.pinimg.com/736x/ef/8c/cb/ef8ccb18651fff2d5372d7e06509bade.jpg',
            largeImg: 'https://i.pinimg.com/736x/20/ca/90/20ca90bc70071f06c3d1166c4a8cbf2d.jpg',
            event: 'PK vs MI',
            img1: PK,
            img2: MI,
            team1: pk,
            team2: mi,
            date: 'SUN 11',
            time: '03:30 P.M',
            month: 'May',
            venue: 'Himachal Pradesh Cricket Association Stadium',
            location: 'Dharamshala, India',
            address: 'HPCA Cricket Stadium, Distt-Kangra, Tehsil, Jawahar Nagar, Dharamshala, Himachal Pradesh 176215, India',
            game:'Cricket',
            duration:3,
            tickets: 2,
            layout: 'Outdoor',
            seating:'Seated',
            kids: 'Yes',
            on: '2025-05-11',
            type: 'IPL',
            priceStarts: 1000,
            des: `The Punjab Kings return to action at the iconic Dharamshala stadium, set to face the Delhi Capitals in a high-stakes clash. Under Shreyas Iyer’s sharp captaincy, PBKS will be aiming to make a statement at home. Prabhsimran’s fearless batting, Shashank’s finishing, and Arshdeep’s brilliance with the ball have kept them in the hunt. Add Chahal’s spin mastery, and Punjab looks ready for any challenge. Delhi, led by Axar and backed by KL Rahul and Kuldeep Yadav, brings serious firepower. But in the shadow of the Himalayas, with the crowd roaring and Shreyas leading from the front, another win in red and gold could be on the horizon. With the playoff race tightening, every ball will count in this adrenaline-charged showdown. Expect fireworks as two explosive lineups collide under the Dharamsala lights, where legends are made and dreams come alive.`
        },
        {
            id: 10,
            img: 'https://i.pinimg.com/736x/f2/cb/4f/f2cb4f28f77bfa597f79fa2163503ca2.jpg',
            largeImg: 'https://i.pinimg.com/736x/17/5c/64/175c6404a925b3bd1b25767a7e5ce550.jpg',
            event: 'DC vs GT',
            img1: DC,
            img2: GT,
            team1: dc,
            team2: gt,
            date: 'SUN 11',
            time: '07:30 P.M',
            month: 'May',
            venue: 'Arun Jaitley Stadium',
            location: 'Delhi, India',
            address: 'Jawaharlal Nehru Marg, Feroze Shah Kotla, Raj Ghat, New Delhi, Delhi, 110002',
            game:'Cricket',
            duration:3,
            tickets: 2,
            layout: 'Outdoor',
            seating:'Seated',
            kids: 'Yes',
            on: '2025-05-11',
            type: 'IPL',
            priceStarts: 1000,
            des: `The Punjab Kings return to action at the iconic Dharamshala stadium, set to face the Delhi Capitals in a high-stakes clash. Under Shreyas Iyer’s sharp captaincy, PBKS will be aiming to make a statement at home. Prabhsimran’s fearless batting, Shashank’s finishing, and Arshdeep’s brilliance with the ball have kept them in the hunt. Add Chahal’s spin mastery, and Punjab looks ready for any challenge. Delhi, led by Axar and backed by KL Rahul and Kuldeep Yadav, brings serious firepower. But in the shadow of the Himalayas, with the crowd roaring and Shreyas leading from the front, another win in red and gold could be on the horizon. With the playoff race tightening, every ball will count in this adrenaline-charged showdown. Expect fireworks as two explosive lineups collide under the Dharamsala lights, where legends are made and dreams come alive.`
        },
        {
            id: 11,
            img: 'https://i.pinimg.com/736x/86/8a/ee/868aee08987220c64fbcde1e33b8fcc6.jpg',
            largeImg: 'https://i.pinimg.com/736x/81/f5/42/81f542e50a0b8b6475b9d286e6694518.jpg',
            event: 'RR vs CSK',
            img1: RR,
            img2: CSK,
            team1: rr,
            team2: csk,
            date: 'MON 12',
            time: '07:30 P.M',
            month: 'May',
            venue: 'Arun Jaitley Stadium',
            location: 'Chennai, India',
            address: '1, Wallahjah Rd, Chepauk, Triplicane, Chennai, Tamil Nadu 600002',
            game:'Cricket',
            duration:3,
            tickets: 2,
            layout: 'Outdoor',
            seating:'Seated',
            kids: 'Yes',
            on: '2025-05-12',
            type: 'IPL',
            priceStarts: 1000,
            des: `The Punjab Kings return to action at the iconic Dharamshala stadium, set to face the Delhi Capitals in a high-stakes clash. Under Shreyas Iyer’s sharp captaincy, PBKS will be aiming to make a statement at home. Prabhsimran’s fearless batting, Shashank’s finishing, and Arshdeep’s brilliance with the ball have kept them in the hunt. Add Chahal’s spin mastery, and Punjab looks ready for any challenge. Delhi, led by Axar and backed by KL Rahul and Kuldeep Yadav, brings serious firepower. But in the shadow of the Himalayas, with the crowd roaring and Shreyas leading from the front, another win in red and gold could be on the horizon. With the playoff race tightening, every ball will count in this adrenaline-charged showdown. Expect fireworks as two explosive lineups collide under the Dharamsala lights, where legends are made and dreams come alive.`
        },
        {
            id: 12,
            img: 'https://i.pinimg.com/736x/cc/3a/d0/cc3ad0145415b6fd1a419e87d9fc338e.jpg',
            largeImg: 'https://i.pinimg.com/736x/cf/24/0d/cf240d13ad615152fdef09ce67c0d553.jpg',
            event: 'GT vs CSK',
            img1: GT,
            img2: CSK,
            team1: gt,
            team2: csk,
            date: 'SUN 18',
            time: '03:30 P.M',
            month: 'May',
            venue: 'Narendra Modi Stadium',
            location: 'Ahmedabad, India',
            address: 'Stadium Road Motera, Sabarmati, Ahmedabad, Gujarat 380005',
            game:'Cricket',
            duration:3,
            tickets: 2,
            layout: 'Outdoor',
            seating:'Seated',
            kids: 'Yes',
            on: '2025-05-17',
            type: 'IPL',
            priceStarts: 499,
            des: `The Punjab Kings return to action at the iconic Dharamshala stadium, set to face the Delhi Capitals in a high-stakes clash. Under Shreyas Iyer’s sharp captaincy, PBKS will be aiming to make a statement at home. Prabhsimran’s fearless batting, Shashank’s finishing, and Arshdeep’s brilliance with the ball have kept them in the hunt. Add Chahal’s spin mastery, and Punjab looks ready for any challenge. Delhi, led by Axar and backed by KL Rahul and Kuldeep Yadav, brings serious firepower. But in the shadow of the Himalayas, with the crowd roaring and Shreyas leading from the front, another win in red and gold could be on the horizon. With the playoff race tightening, every ball will count in this adrenaline-charged showdown. Expect fireworks as two explosive lineups collide under the Dharamsala lights, where legends are made and dreams come alive.`
        },
        {
            id: 13,
            img: 'https://i.pinimg.com/736x/20/88/22/2088221f1f7533a806ef854ef3e3e6bd.jpg',
            largeImg: 'https://i.pinimg.com/736x/e3/ff/6b/e3ff6bc77507a39a30f38ae306d0f5e4.jpg',
            event: 'LSG vs SRH',
            img1: LSG,
            img2: SRH,
            team1: lsg,
            team2: srh,
            date: 'SUN 18',
            time: '07:30 P.M',
            month: 'May',
            venue: 'Ekana Cricket Stadium',
            location: 'Uttar Pradesh, India',
            address: 'Ekana Sportz City, Gomti Nagar, Lucknow, Ardonamau, Uttar Pradesh 226010',
            game:'Cricket',
            duration:3,
            tickets: 2,
            layout: 'Outdoor',
            seating:'Seated',
            kids: 'Yes',
            on: '2025-05-17',
            type: 'IPL',
            priceStarts: 1000,
            des: `The Punjab Kings return to action at the iconic Dharamshala stadium, set to face the Delhi Capitals in a high-stakes clash. Under Shreyas Iyer’s sharp captaincy, PBKS will be aiming to make a statement at home. Prabhsimran’s fearless batting, Shashank’s finishing, and Arshdeep’s brilliance with the ball have kept them in the hunt. Add Chahal’s spin mastery, and Punjab looks ready for any challenge. Delhi, led by Axar and backed by KL Rahul and Kuldeep Yadav, brings serious firepower. But in the shadow of the Himalayas, with the crowd roaring and Shreyas leading from the front, another win in red and gold could be on the horizon. With the playoff race tightening, every ball will count in this adrenaline-charged showdown. Expect fireworks as two explosive lineups collide under the Dharamsala lights, where legends are made and dreams come alive.`
        },
        
    ],

    football:[
        {
            id:1,
        }
    ],

    chess:[
        {
            id:1, 
            name:'Chess-Chai-Connect',
            game:'Chess', 
            duration: 3 , 
            tickets: 2, 
            layout: 'Indoor', 
            seating:'Seated', 
            kids: 'Yes', 
            price:[750, 1550, 1850, 3500, 6500, 12500, 15000],
        }
    ]
        
    }
]

export default SportsLists;